# Generated by Django 5.0.3 on 2024-03-23 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_id', models.CharField(default='36e287df', editable=False, max_length=8, unique=True)),
                ('so_pass', models.CharField(default='9dd1e509', editable=False, max_length=8, unique=True)),
                ('accept_date', models.DateField(auto_now_add=True, null=True)),
                ('device_type', models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('printer', 'Printer')], max_length=20)),
                ('device_data', models.CharField(max_length=200)),
                ('issue_description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('closed', 'Closed')], max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_complete', models.DateField(auto_now=True, null=True)),
                ('resolution_description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.serviceorder')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
