# Generated by Django 5.0.3 on 2024-03-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='accept_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='90526d98', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_pass',
            field=models.CharField(default='95e4a775', max_length=8, unique=True),
        ),
    ]
