# Generated by Django 5.0.3 on 2024-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_alter_serviceorder_accept_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='accept_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='8f415e2b', editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_pass',
            field=models.CharField(default='0dc98504', editable=False, max_length=8, unique=True),
        ),
    ]
