# Generated by Django 5.0.3 on 2024-03-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('reception', '0004_alter_serviceorder_accept_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='84111247f4904461', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_pass',
            field=models.CharField(default='2022daa487064d94', editable=False, max_length=20, unique=True),
        ),
    ]
