# Generated by Django 5.0.3 on 2024-03-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('reception', '0005_alter_serviceorder_client_alter_serviceorder_so_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='so_pass',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='a1cb2f90', editable=False, max_length=20, unique=True),
        ),
    ]
