# Generated by Django 5.0.3 on 2024-03-26 07:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('reception', '0008_alter_serviceorder_accept_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='accept_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='f7a29fe9', editable=False, max_length=20, unique=True),
        ),
    ]
