# Generated by Django 5.0.3 on 2024-03-26 12:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('reception', '0013_alter_serviceorder_client_alter_serviceorder_so_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='4730499a', editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='OrdersHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('date_of_complete', models.DateField(blank=True, default=datetime.date.fromisocalendar, null=True)),
                ('resolution_description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.serviceorder')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceOrderHistory',
        ),
    ]
