# Generated by Django 5.0.3 on 2024-03-26 13:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
        ('reception', '0014_alter_serviceorder_client_alter_serviceorder_so_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='date_of_complete',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(default=(), on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='so_id',
            field=models.CharField(default='1e680eb2', editable=False, max_length=20, unique=True),
        ),
    ]
