# Generated by Django 5.0.3 on 2024-04-19 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0024_alter_ordershistory_date_of_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='date_of_complete',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
