# Generated by Django 5.0.3 on 2024-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0028_alter_serviceorder_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
