# Generated by Django 5.0.3 on 2024-03-22 18:36

import django.core.validators
import tools.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_smsuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(9), tools.validators.phone_validator]),
        ),
    ]
