# Generated by Django 5.0.3 on 2024-03-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-pk',)},
        ),
    ]
