# Generated by Django 5.0.3 on 2024-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('printer', 'Printer')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
