# Generated by Django 5.0.3 on 2024-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
