# Generated by Django 5.0.3 on 2024-03-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
