# Generated by Django 5.0.3 on 2024-03-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_serviceinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='device',
            field=models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('printer', 'Printer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
